apiVersion: v1
kind: Service
metadata:
  name: personal-budget-app
  namespace: personal-budget-app
spec:
  selector:
    app: personal-budget-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
