apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: personal-budget-db-cluster
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1



  bootstrap:
    initdb:
      database: personal_budget_user
      owner: personal_budget_user
      secret:
        name: personal-budget-user-secret

  storage:
    size: 10Gi