definitions:
  models.Budget:
    properties:
      amount:
        type: number
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /budgets:
    get:
      description: Get all budgets from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Budget'
            type: array
      summary: Get all budgets
      tags:
      - Budgets
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Insert a new budget into the database
      parameters:
      - description: Budget Name
        in: formData
        name: name
        required: true
        type: string
      - description: Budget Amount
        in: formData
        name: amount
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Insert a new budget
      tags:
      - Budgets
  /budgets/{id}:
    get:
      description: Get a single budget by ID from the database
      parameters:
      - description: Budget ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Budget'
      summary: Get a single budget
      tags:
      - Budgets
  /budgets/add:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Add an amount to an existing budget
      parameters:
      - description: Budget ID
        in: formData
        name: id
        required: true
        type: integer
      - description: Amount to add
        in: formData
        name: amount
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Add to a budget
      tags:
      - Budgets
  /budgets/spend:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Spend an amount from an existing budget
      parameters:
      - description: Budget ID
        in: formData
        name: id
        required: true
        type: integer
      - description: Amount to spend
        in: formData
        name: amount
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Spend from a budget
      tags:
      - Budgets
  /health:
    get:
      description: Check if the server is running and healthy
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Check the health of the server
      tags:
      - Health
  /ping:
    get:
      description: Ping the server to check if it's running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ping the server
      tags:
      - Health
swagger: "2.0"
