name: CI Pipeline

# This CI pipeline automates the testing, linting, and Docker image creation process for the Go application.
# It includes:
# 1. Setting up a PostgreSQL database service for integration tests.
# 2. Running Go linters and tests to ensure code quality.
# 3. Building a Docker image of the application.
# 4. Scanning the Docker image for vulnerabilities.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install linter and tools
        run: |
          go install golang.org/x/lint/golint@latest
          curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          echo "PATH=$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV

      - name: Install dependencies
        run: go mod tidy

      - name: Run linters
        run: |
          golint ./...
          go vet ./...
          gofmt -s -d .

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U testuser; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
          echo "PostgreSQL is ready!"

      - name: Initialize database schema
        run: |
          PGPASSWORD=testpassword psql -h localhost -p 5432 -U testuser -d testdb <<EOF
          CREATE TABLE IF NOT EXISTS personal_budget (
              id SERIAL PRIMARY KEY,
              name TEXT NOT NULL,
              amount NUMERIC(10, 2) NOT NULL,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );
          EOF

        # Create .env file to successfully pass the Docker build action
      - name: Create .env file
        run: echo "DATABASE_URL=postgres://testuser:testpassword@localhost:5432/testdb" > .env


      - name: Export DATABASE_URL for testing
        run: echo "DATABASE_URL=postgres://testuser:testpassword@localhost:5432/testdb" >> $GITHUB_ENV

      - name: Run tests
        run: go test ./... -v

      - name: Build Docker image
        run: docker build -t personal-budget:latest .

      - name: Scan Docker image
        run: trivy image personal-budget:latest
